{
 "title": "Evidently Metrics",
 "description": "Using prefect to run daily predictions for 27 days",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Drifted columns",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(num_drifted_columns) FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}